version: '3'
services:
  db:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx
    volumes: 
      - /data/html:/var/www/html
    ports: 
      - 443:443
  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    depends on:
      - db
    image: wordpress
    env_file:
      - .env
    volumes:
      - data/html:/var/www/html
    ports:
      - 9000:9000
    restart: always
     
network:
  

# volumes:
#   db_volume:
#     -/data/mysql
#   wordpress_volume:
#     -/data/hmtl