version: '3'
services:
  db:
    build:
      context: .
      dockerfile: mariadb/dockerfile
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mbadaoui
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/dockerfile
    image: nginx
    volumes: 
      - nginx: /etc/nginx/nginx.conf
      - /data/html: /var/www/html
    ports: 
      - 443:443