version: '3'

networks:
  hadnetwork:
    name: hadnetwork
    driver: bridge

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbadaoui/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbadaoui/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - hadnetwork
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - hadnetwork
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - hadnetwork
    restart: unless-stopped
