version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    depends_on:
      - mariadb
    image: wordpress
    env_file:
      - .env
    volumes:
      - /data/html:/var/www/html
    ports:
      - 9000:9000
    networks:
      - mynetwork
    restart: always
  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - mynetwork
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx
    volumes: 
      - /data/html:/var/www/html
    ports: 
      - 443:443
    networks:
      - mynetwork
     
networks:
  mynetwork:
    driver: bridge

# volumes:
#   db_volume:
#     -/data/mysql
#   wordpress_volume:
#     -/data/hmtl