version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    depends_on:
      - mariadb
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - mynetwork
    restart: always
  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    image: mariadb
    volumes:
      - db_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mynetwork
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx
    volumes: 
      - wordpress_volume:/var/www/html
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    networks:
      - mynetwork
     restart: always
     
networks:
  mynetwork:
    driver: bridge

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbadaoui/data/mariadb
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbadaoui/data/wordpress
