version: '3.5'

networks:
  hadnetwork:
    name: hadnetwork
    driver: bridge

volumes:
  db_volume:
    driver: local
    name: db_volume
    driver_opts:
      type: none
      o: bind
      device: /home/mbadaoui/data/mariadb
  wordpress_volume:
    driver: local
    name: wordpress_volume
    driver_opts:
      type: none
      o: bind
      device: /home/mbadaoui/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./mariadb
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASSE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - hadnetwork
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: 
      context: ./wordpress
      args:
        WORDPRESS_TITLE: ${WORDPRESS_TITLE}
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_USER: ${WORDPRESS_USER}
        WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
        WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - hadnetwork
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - hadnetwork
    restart: unless-stopped
