version: '3'
services:
  db:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx
    volumes: 
      - /data/html:/var/www/html
    ports: 
      - 443:443
